FROM kafka-manager:latest

#USER root
#ADD ./conf/ /opt/sonarqube/conf/
#ADD ./plugins/ /opt/sonarqube/extensions/plugins/
#RUN chown -R sonarqube:sonarqube /opt/sonarqube/extensions/plugins

EXPOSE 9020 9021
